"""Original procedural GAME100 demo audio. No samples or external compositions.
Run: python3 scripts/generate-audio.py (Python stdlib only).
PCM mono 22050 Hz; periodic BGM tails wrap over the loop boundary.
"""
from pathlib import Path
import math, wave, struct, random, json
ROOT = Path(__file__).resolve().parents[1]
RATE = 22050
rng = random.Random(100)
def tone(buf, start, dur, freq, amp=.2, bright=.15, noise=0, sweep=0, wrap=False):
    phase = 0
    for i in range(int(dur*RATE)):
        t=i/RATE; u=t/dur
        phase += 2*math.pi*freq*(1+sweep*u)/RATE
        env=min(1,t/.006)*max(0,1-u)**2
        v=(math.sin(phase)+bright*math.sin(phase*2)+noise*rng.uniform(-1,1))*amp*env
        j=int(start*RATE)+i
        if wrap: j %= len(buf)
        if j<len(buf): buf[j]+=v

def write(path, buf):
    peak=max(abs(x) for x in buf) or 1
    gain=min(1,.78/peak)
    with wave.open(str(ROOT/'assets/audio'/path),'wb') as f:
        f.setparams((1,2,RATE,0,'NONE','not compressed'))
        f.writeframes(b''.join(struct.pack('<h',round(max(-1,min(1,v*gain))*32767)) for v in buf))
    return round(len(buf)/RATE*1000)

# Unique cues: notes / spacing / duration / timbre.
cues={
'ui':('common',[760],.04,.065,.06), 'start':('common',[440,660,880],.075,.15,.22),
'over':('common',[330,262,196],.12,.27,.16), 'best':('common',[523,659,784,1047],.12,.3,.25),
'warning':('common',[210],.04,.09,.09),
'move':('game001',[400],.02,.035,.025),'rotate':('game001',[480,720],.035,.07,.08),
'drop':('game001',[95],.03,.18,.32),'lock':('game001',[260],.02,.065,.12),
'line1':('game001',[523,659],.065,.16,.18),'line2':('game001',[523,659,784],.065,.2,.2),
'line3':('game001',[659,784,988],.075,.25,.22),'line4':('game001',[523,659,784,1047,1319],.07,.3,.24),
'level':('game001',[392,523,784],.09,.22,.19),
'break1':('game002',[360],.03,.085,.2),'break2':('game002',[450],.03,.085,.2),
'break3':('game002',[570],.03,.1,.21),'break4':('game002',[720,1080],.02,.12,.22),
'fever':('game002',[440,554,659,880],.06,.2,.22),'feverEnd':('game002',[660,440],.07,.12,.12),
'pickup':('game002',[980],.03,.09,.12),'multi':('game002',[440,660,880,1320],.035,.16,.18),
'wide':('game002',[330,440,550],.07,.15,.18),'power':('game002',[196,392,784],.05,.22,.2),
'miss':('game002',[290,220],.07,.12,.12),'clear':('game002',[523,659,784,1047],.11,.28,.22),
'allClear':('game002',[523,659,784,1047,784,1047,1319],.13,.4,.23),
'place1':('game003',[600],.03,.075,.13),'place2':('game003',[400],.03,.1,.15),
'place3':('game003',[240],.03,.14,.18),'cover':('game003',[120,540],.035,.16,.22),
'win':('game003',[523,659,784,1047],.1,.3,.19),'draw':('game003',[392,440,392],.09,.17,.12),
'pathMove':('game004',[510],.02,.075,.075),
'pathJump':('game004',[390,590,880],.035,.1,.10),
'pathWall':('game004',[110,440],.025,.20,.19),
'pathGoal':('game004',[494,587,740,988,1175],.115,.32,.19),
'slingGrab':('game005',[820],.02,.045,.055),
'slingShot':('game005',[240,720],.025,.13,.16),
'slingHit':('game005',[160],.02,.07,.12),
'slingGate':('game005',[660,990],.05,.14,.15),
'slingWin':('game005',[494,622,740,988,1245],.105,.32,.21),
'slingTick':('game005',[560],.02,.055,.07),
}
manifest={}
for name,(folder,notes,spacing,duration,amp) in cues.items():
    buf=[0.] * int(((len(notes)-1)*spacing+duration+.01)*RATE)
    for i,freq in enumerate(notes):
        tone(buf,i*spacing,duration,freq,amp,.25, .3 if name.startswith('break') or name=='drop' else 0, -.4 if name=='drop' else 0)
    path=f'{folder}/{name}.wav'; ms=write(path,buf)
    manifest[name]={'path':path,'ms':ms}
# Dedicated compositions: distinct melodies, harmonic rhythm and instruments.
import runpy
scores = runpy.run_path(str(ROOT/'scripts/compose-bgm.py'))['compose']()
for scene, buf in scores.items():
    folder='common' if scene=='home' else 'game'+scene
    path=f'{folder}/bgm.wav'; ms=write(path,buf)
    manifest['bgm'+scene]={'path':path,'ms':ms}
(ROOT/'assets/audio/manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
lines=['// Generated by scripts/generate-audio.py. Original procedural demo sounds.','export const sources = {']
for name,v in manifest.items(): lines.append(f'  {name}: require("../../assets/audio/{v["path"]}"),')
lines+=['} as const;','export type SoundId = keyof typeof sources;', 'export const durations: Record<SoundId, number> = '+json.dumps({k:v['ms'] for k,v in manifest.items()})+';']
(ROOT/'src/audio/sounds.ts').write_text('\n'.join(lines)+'\n')
print(f'Generated {len(manifest)} original WAVs')
